from __future__ import annotations

import re
import unicodedata


COUNTRY_FORMULA_CODE_TO_NAME = {
    "AF": "AFGHANISTAN",
    "AL": "ALBANIA",
    "DZ": "ALGERIA",
    "AD": "ANDORRA",
    "AO": "ANGOLA",
    "AI": "ANGUILLA",
    "AG": "ANTIGUA AND BARBUDA",
    "AR": "ARGENTINA",
    "AM": "ARMENIA",
    "AW": "ARUBA",
    "AX": "ASCENSION",
    "AU": "AUSTRALIA",
    "AT": "AUSTRIA",
    "AZ": "AZERBAIJAN",
    "BS": "BAHAMAS",
    "BH": "BAHRAIN",
    "BD": "BANGLADESH",
    "BB": "BARBADOS",
    "BY": "BELARUS",
    "BE": "BELGIUM",
    "BZ": "BELIZE",
    "BJ": "BENIN",
    "BM": "BERMUDA",
    "BT": "BHUTAN",
    "BO": "BOLIVIA",
    "BQ": "BONAIRE SABA AND SINT EUSTATIUS",
    "BA": "BOSNIA AND HERZEGOVINA",
    "BW": "BOTSWANA",
    "BR": "BRAZIL",
    "VG": "BRITISH VIRGIN ISLANDS",
    "BN": "BRUNEI",
    "BG": "BULGARIA",
    "BF": "BURKINA FASO",
    "BI": "BURUNDI",
    "KH": "CAMBODIA",
    "CM": "CAMEROON",
    "CA": "CANADA",
    "CV": "CAPE VERDE",
    "KY": "CAYMAN",
    "CF": "CENTRAL AFRICA",
    "TD": "CHAD",
    "CL": "CHILE",
    "CN": "CHINA",
    "CX": "CHRISTMAS ISLAND",
    "CC": "COCOS ISLANDS",
    "CO": "COLOMBIA",
    "KM": "COMOROS",
    "CG": "CONGO",
    "CK": "COOK ISLANDS",
    "CR": "COSTA RICA",
    "CI": "COTE D'IVOIRE",
    "HR": "CROATIA",
    "CU": "CUBA",
    "CW": "CURACAO",
    "CY": "CYPRUS",
    "CZ": "CZECH",
    "KP": "D.P.R. KOREA",
    "CD": "D.R. CONGO",
    "DK": "DENMARK",
    "DJ": "DJIBOUTI",
    "DO": "DOMINICAN REPUBLIC",
    "DM": "DOMINICA",
    "TL": "EAST TIMOR",
    "EC": "ECUADOR",
    "EG": "EGYPT",
    "SV": "EL SALVADOR",
    "GQ": "EQUATORIAL GUINEA",
    "ER": "ERITREA",
    "EE": "ESTONIA",
    "SZ": "ESWATINI",
    "ET": "ETHIOPIA",
    "FK": "FALKLAND",
    "FO": "FAROE ISLANDS",
    "FJ": "FIJI",
    "FI": "FINLAND",
    "FR": "FRANCE",
    "GF": "FRENCH GUIANA",
    "PF": "FRENCH POLYNESIA",
    "TF": "FRENCH SOUTHERN AND ANTARCTIC TERRITORIES",
    "GA": "GABON",
    "GM": "GAMBIA",
    "GE": "GEORGIA",
    "DE": "GERMANY",
    "GH": "GHANA",
    "GI": "GIBRALTAR",
    "GR": "GREECE",
    "GL": "GREENLAND",
    "GD": "GRENADA",
    "GP": "GUADELOUPE",
    "GU": "GUAM",
    "GT": "GUATEMALA",
    "GG": "GUERNSEY",
    "GW": "GUINEA-BISSAU",
    "GN": "GUINEA",
    "GY": "GUYANA",
    "HT": "HAITI",
    "HN": "HONDURAS",
    "HK": "HONG KONG",
    "HU": "HUNGARY",
    "IS": "ICELAND",
    "IN": "INDIA",
    "ID": "INDONESIA",
    "IR": "IRAN",
    "IQ": "IRAQ",
    "IE": "IRELAND",
    "IM": "ISLE OF MAN",
    "IL": "ISRAEL",
    "IT": "ITALY",
    "JM": "JAMAICA",
    "JE": "JERSEY",
    "JO": "JORDAN",
    "KZ": "KAZAKHSTAN",
    "KE": "KENYA",
    "KI": "KIRIBATI",
    "KR": "KOREA",
    "XZ": "KOSOVO",
    "KW": "KUWAIT",
    "KG": "KYRGYZ",
    "LA": "LAOS",
    "LV": "LATVIA",
    "LB": "LEBANON",
    "LS": "LESOTHO",
    "LR": "LIBERIA",
    "LY": "LIBYA",
    "LI": "LIECHTENSTEIN",
    "LT": "LITHUANIA",
    "LU": "LUXEMBOURG",
    "MO": "MACAO",
    "MG": "MADAGASCAR",
    "MW": "MALAWI",
    "MY": "MALAYSIA",
    "MV": "MALDIVES",
    "ML": "MALI",
    "MT": "MALTA",
    "MH": "MARSHALL ISLANDS",
    "MQ": "MARTINIQUE",
    "MR": "MAURITANIA",
    "MU": "MAURITIUS",
    "YT": "MAYOTTE",
    "MX": "MEXICO",
    "FM": "MICRONESIA",
    "UM": "MIDWAY ISLANDS",
    "MD": "MOLDOVA",
    "MC": "MONACO",
    "MN": "MONGOLIA",
    "ME": "MONTENEGRO",
    "MS": "MONTSERRAT",
    "MA": "MOROCCO",
    "MZ": "MOZAMBIQUE",
    "MM": "MYANMAR",
    "NA": "NAMIBIA",
    "NR": "NAURU",
    "NP": "NEPAL",
    "NL": "NETHERLANDS",
    "NC": "NEW CALEDONIA",
    "NZ": "NEW ZEALAND",
    "NI": "NICARAGUA",
    "NG": "NIGERIA",
    "NE": "NIGER",
    "NF": "NORFOLK ISLAND",
    "NT": "NORTH ISLANDS",
    "MK": "NORTH MACEDONIA",
    "MP": "NORTHERN MARIANA ISLANDS",
    "NO": "NORWAY",
    "OM": "OMAN",
    "PK": "PAKISTAN",
    "PW": "PALAU",
    "PA": "PANAMA",
    "PG": "PAPUA NEW GUINEA",
    "PY": "PARAGUAY",
    "PE": "PERU",
    "PH": "PHILIPPINES",
    "PN": "PITCAIRNIS",
    "PL": "POLAND",
    "PT": "PORTUGAL",
    "PR": "PUERTO RICO",
    "QA": "QATAR",
    "RE": "REUNION",
    "RO": "ROMANIA",
    "RU": "RUSSIA",
    "RW": "RWANDA",
    "LC": "SAINT LUCIA",
    "SX": "SAINT MAATIN",
    "SP": "SAIPAN",
    "AS": "SAMOA",
    "WS": "SAMOA",
    "SM": "SAN MARINO",
    "ST": "SAO TOME AND PRINCIPE",
    "SA": "SAUDI ARABIA",
    "SN": "SENEGAL",
    "RS": "SERBIA",
    "SC": "SEYCHELLES",
    "SL": "SIERRA LEONE",
    "SG": "SINGAPORE",
    "SK": "SLOVAKIA",
    "SI": "SLOVENIA",
    "SB": "SOLOMONS",
    "SO": "SOMALIA",
    "ZA": "SOUTH AFRICA",
    "SS": "SOUTH SUDAN",
    "ES": "SPAIN",
    "LK": "SRI LANKA",
    "KN": "ST CHRISTOPHER AND NEVIS",
    "VC": "ST VINCENT",
    "SH": "ST. HELENA",
    "PM": "ST. PIERRE AND MIQUELON",
    "SD": "SUDAN",
    "SR": "SURINAME",
    "SE": "SWEDEN",
    "CH": "SWITZERLAND",
    "SY": "SYRIA",
    "TW": "TAIWAN",
    "TJ": "TAJIKISTAN",
    "TZ": "TANZANIA",
    "TH": "THAILAND",
    "TG": "TOGO",
    "TO": "TONGA",
    "TT": "TRINIDAD AND TOBAGO",
    "TA": "TRISTAN DA CUNHA",
    "TN": "TUNISIA",
    "TR": "TURKEY",
    "TM": "TURKMENISTAN",
    "TC": "TURKS AND CAICOS",
    "TV": "TUVALU",
    "XY": "U.S. MILITARY BASE IN JAPAN",
    "UG": "UGANDA",
    "UA": "UKRAINE",
    "AE": "UNITED ARAB EMIRATES",
    "GB": "UNITED KINGDOM",
    "US": "UNITED STATES OF AMERICA",
    "UY": "URUGUAY",
    "VI": "US VIRGIN ISLANDS",
    "UZ": "UZBEKISTAN",
    "VU": "VANUATU",
    "VA": "VATICAN",
    "VE": "VENEZUELA",
    "VN": "VIET NAM",
    "WK": "WAKE ISLANDS",
    "WF": "WALLIS AND FUTUNA",
    "YE": "YEMEN",
    "ZM": "ZAMBIA",
    "ZW": "ZIMBABWE",
}

EUROPE_COUNTRY_CODES = {
    "AL", "AD", "AM", "AT", "AZ", "BY", "BE", "BA", "BG", "HR", "CY", "CZ",
    "DK", "EE", "FO", "FI", "FR", "GE", "DE", "GI", "GR", "GG", "HU", "IS",
    "IE", "IM", "IT", "JE", "XZ", "LV", "LI", "LT", "LU", "MT", "MD", "MC",
    "ME", "NL", "MK", "NO", "PL", "PT", "RO", "RU", "SM", "RS", "SK", "SI",
    "ES", "SE", "CH", "TR", "UA", "GB", "VA",
}

COUNTRY_FORMULA_NAME_TO_CODE = {
    name.upper(): code for code, name in COUNTRY_FORMULA_CODE_TO_NAME.items()
}


def normalize_country_name(value: str) -> str:
    text = unicodedata.normalize("NFKC", str(value or "")).strip()
    text = re.split(r"[\(\uFF08嚗]", text, maxsplit=1)[0].strip()
    text = re.sub(r"[^A-Za-z0-9.'& -]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip().upper()
    return text


def resolve_country_code(country_raw: str, exact_map: dict[str, str] | None = None) -> str:
    text = str(country_raw or "").strip()
    if not text:
        return ""

    if exact_map:
        if text in exact_map:
            return exact_map[text]
        upper_map = {str(key).upper(): value for key, value in exact_map.items()}
        mapped = upper_map.get(text.upper())
        if mapped:
            return mapped

    normalized = normalize_country_name(text)
    if not normalized:
        return ""
    if normalized in {"EU", "EUROPE"}:
        return "EU"
    if normalized in COUNTRY_FORMULA_CODE_TO_NAME:
        code = normalized
    else:
        code = COUNTRY_FORMULA_NAME_TO_CODE.get(normalized, "")
    if not code:
        return ""
    if code in EUROPE_COUNTRY_CODES:
        return "EU"
    return code
