[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#5275A8"
backgroundColor = "#0B0D10"
secondaryBackgroundColor = "#15171B"
textColor = "#F8FAFC"
font = "sans serif"

[browser]
gatherUsageStats = false
