[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#C0392B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
font = "sans serif"

[browser]
gatherUsageStats = false
